@startuml
start
:Initialize table, x = a;
repeat
  :x <= b?;
  if (x < 2.2?) then (yes)
    :Call func_one(x);
  else (no)
    if (x < 3?) then (yes)
      :Call func_two(x);
    else (no)
      :Call func_three(x);
    endif
  endif
  :Update table;
  :Increment x by h;
repeat while (x <= b)
stop
@enduml
